[manager]
address = "127.0.0.1:50051"
retry_interval_s = 5

[service]
name = "picoscope-service"
description = "PicoScope oscilloscope acquisition and configuration service"
address = "100.114.164.102:50055"
